-- Example of a database setup with some roles.
-- Privileges would be better defined in a real setup.
-- Code was used in Snowflake.

USE ROLE ACCOUNTADMIN;
GRANT ALL Privileges ON DATABASE MAIN TO SYSADMIN;
GRANT ALL Privileges ON ALL SCHEMAS IN DATABASE MAIN TO SYSADMIN;
GRANT ALL Privileges ON FUTURE SCHEMAS IN DATABASE MAIN TO SYSADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE MAIN TO SYSADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE MAIN TO SYSADMIN;

CREATE OR REPLACE ROLE ENGINEER; 
GRANT ALL Privileges ON DATABASE MAIN TO ENGINEER;
GRANT ALL Privileges ON ALL SCHEMAS IN DATABASE MAIN TO ENGINEER;
GRANT ALL Privileges ON FUTURE SCHEMAS IN DATABASE MAIN TO ENGINEER;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE MAIN TO ENGINEER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE MAIN TO ENGINEER;

GRANT ROLE ENGINEER TO ROLE SYSADMIN;

CREATE OR REPLACE ROLE ANALYST; 
GRANT ALL Privileges ON DATABASE MAIN TO ANALYST;
GRANT ALL Privileges ON ALL SCHEMAS IN DATABASE MAIN TO ANALYST;
GRANT ALL Privileges ON FUTURE SCHEMAS IN DATABASE MAIN TO ANALYST;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE MAIN TO ANALYST;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE MAIN TO ANALYST;

GRANT ROLE ANALYST TO ROLE SYSADMIN;

GRANT ALL Privileges ON DATABASE MAIN TO PC_DBT_ROLE;
GRANT ALL Privileges ON ALL SCHEMAS IN DATABASE MAIN TO PC_DBT_ROLE;
GRANT ALL Privileges ON FUTURE SCHEMAS IN DATABASE MAIN TO PC_DBT_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE MAIN TO PC_DBT_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE MAIN TO PC_DBT_ROLE;

GRANT ROLE PC_DBT_ROLE TO ROLE SYSADMIN;
GRANT ROLE PC_DBT_ROLE TO USER PC_DBT_USER;


CREATE SCHEMA IF NOT EXISTS MAIN.RAW;
CREATE SCHEMA IF NOT EXISTS MAIN.BRONZE;
CREATE SCHEMA IF NOT EXISTS MAIN.SILVER;
CREATE SCHEMA IF NOT EXISTS MAIN.GOLD;
